// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuduSimulator.Data;

#nullable disable

namespace PuduSimulator.Migrations
{
    [DbContext(typeof(PuduDbContext))]
    [Migration("20250531080107_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PuduSimulator.Models.DiscordServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("DiscordServers");
                });

            modelBuilder.Entity("PuduSimulator.Models.Pudu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscordServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordServerId")
                        .IsUnique();

                    b.ToTable("Pudus");
                });

            modelBuilder.Entity("PuduSimulator.Models.ServerRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeadPudus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscordServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleasedPudus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordServerId")
                        .IsUnique();

                    b.ToTable("ServerRecords");
                });

            modelBuilder.Entity("PuduSimulator.Models.Pudu", b =>
                {
                    b.HasOne("PuduSimulator.Models.DiscordServer", null)
                        .WithOne("CurrentPudu")
                        .HasForeignKey("PuduSimulator.Models.Pudu", "DiscordServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuduSimulator.Models.ServerRecords", b =>
                {
                    b.HasOne("PuduSimulator.Models.DiscordServer", null)
                        .WithOne("Records")
                        .HasForeignKey("PuduSimulator.Models.ServerRecords", "DiscordServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuduSimulator.Models.DiscordServer", b =>
                {
                    b.Navigation("CurrentPudu");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
